#!/bin/bash
git pull

container_id=$(sudo docker container ls | grep momento | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
	sudo docker container stop $container_id
fi

sudo docker image rm --force momento
sudo docker build -t momento .
sudo docker run -d -v db:/app/db momento
